-- 사업자 여부 추가
ALTER TABLE member ADD COLUMN business_type CHARACTER VARYING(30);

-- 정산 정보 추가
ALTER TABLE member ADD COLUMN bank_name CHARACTER VARYING(255);
ALTER TABLE member ADD COLUMN account_holder CHARACTER VARYING(255);
ALTER TABLE member ADD COLUMN account_number CHARACTER VARYING(255);
ALTER TABLE member ADD COLUMN rrn CHARACTER VARYING(255);
ALTER TABLE member ADD COLUMN bank_account_copy_url CHARACTER VARYING(255);
ALTER TABLE member ADD COLUMN business_license_url CHARACTER VARYING(255);

-- 사업자 정보 추가
ALTER TABLE member ADD COLUMN business_address_detail CHARACTER VARYING(500);