spring:
  config:
    import: classpath:application-secret.properties

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER_NAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: none    # flyway 적용 전까지
    defer-datasource-initialization: true

  sql:
    init:
      mode: never  # PostgreSQL 15 버전 이상 업그레이드 전까지
      encoding: utf-8

encrypt:
  secret: ${DEV_ENCRYPT_SECRET}

file:
  base-url: ${DEV_BASE_URL}
  profile-path: /app/files/upload/profile/
  profile-url: /files/profile/
  studio-path: /app/files/upload/studio/
  project-reference-file-path: /app/files/upload/project/reference/
  project-reference-file-url: /files/project/reference/

jwt:
  secret: ${DEV_JWT_SECRET}

payments:
  toss:
    uri: https://api.tosspayments.com/v1/payments/confirm
    secret-key: ${TOSS_PAYMENT_SECRET}