spring:
  config:
    import: classpath:application-secret.properties

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER_NAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    baseline-version: 1

encrypt:
  secret: ${DEV_ENCRYPT_SECRET}

file:
  base-url: ${DEV_BASE_URL}
  profile-path: /app/files/upload/profile/
  profile-url: /files/profile/
  studio-path: /app/files/upload/studio/
  project-reference-file-path: /app/files/upload/project/reference/
  project-reference-file-url: /files/project/reference/

jwt:
  secret: ${DEV_JWT_SECRET}