spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: root
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

encrypt:
  secret: FKKTQWMSMillz3Jr4pdFUQ==

file:
  base-url: localhost:8080
  profile-path: /Users/fong/files/upload/profile/
  profile-url: /files/profile/
  studio-path: /Users/fong/files/upload/studio/
  project-reference-file-path: /Users/fong/files/upload/project/reference/
  project-reference-file-url: /files/project/reference/

jwt:
  secret: Qb+NiKnqgiFnZnKc7uziuwFX/cq0yzFrJvrpio0JofQ=