server:
  port: 8080

spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 20MB

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    root : info

jwt:
  header: X-AUTH-TOKEN
  access-token-validity-time: 1800000 # milliseconds 30 * 60 * 1000
  refresh-token-validity-time: 86400000 # milliseconds 24 * 60 * 60 * 1000

springdoc:
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    tags-sorter: alpha
