spring:
  config:
    import: classpath:test-secret.properties

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: root
    password:
    driver-class-name: org.h2.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: embedded
      encoding: utf-8

encrypt:
  secret: local_yourplanet

file:
  base-url: localhost:8080
  profile-path: /Users/fong/files/upload/profile/
  profile-url: /files/profile/
  studio-path: /Users/fong/files/upload/studio/
  project-reference-file-path: /Users/fong/files/upload/project/reference/
  project-reference-file-url: /files/project/reference/

jwt:
  secret: YjkwYjNhMjQ3NmM4N2NjYzZkNjUyMzkwNjRhYmExZDk3YjZkNzA4Y

payments:
  toss:
    uri: https://api.tosspayments.com/v1/payments/confirm
    secret-key: ${TEST_TOSS_SECRET_KEY}