server:
  port: 8080

spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 20MB

logging:
  level:
    root : info
    org.hibernate.SQL: debug
    org.hibernate.type: trace # sql 쿼리 input 값 확인하고 싶을 때

jwt:
  header: X-AUTH-TOKEN
  secret: yourplanet
  token-validity-time: 1800000 # milliseconds 30 * 60 * 1000