spring:
  config:
    import: classpath:application-secret.properties

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER_NAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      ssl:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

  cloud:
    config:
      server:
        aws:
          s3:
            region: ${S3_REGION}
            bucket: ${S3_BUCKET_NAME}
            endpoint: ${S3_ENDPOINT}
            credentials:
              access-key: ${S3_ACCESS_KEY}
              secret-key: ${S3_SECRET_KEY}
            expire-time:
              upload: 3600
              download: 600

encrypt:
  secret: ${DEV_ENCRYPT_SECRET}

file:
  base-url: ${DEV_BASE_URL}
  profile-path: /app/files/upload/profile/
  profile-url: /files/profile/
  studio-path: /app/files/upload/studio/
  project-reference-file-path: /app/files/upload/project/reference/
  project-reference-file-url: /files/project/reference/
  base-profile-image-url: ${BASE_PROFILE_IMAGE_URL}

jwt:
  secret: ${DEV_JWT_SECRET}

payments:
  toss:
    uri: https://api.tosspayments.com/v1/payments/confirm
    secret-key: ${TOSS_PAYMENT_SECRET}

omni:
  id: ${OMNI-ALIMTALK-ID}
  password: ${OMNI-ALIMTALK-PASSWORD}
  senderkey: ${OMNI-ALIMTALK-SENDERKEY}
  host: https://omni.ibapi.kr
  url:
    auth: /v1/auth/token
    alimtalk: /v1/send/alimtalk