server:
  port: 8080

spring:
  profiles:
    active: local

logging:
  level:
    root : debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace # sql 쿼리 input 값 확인하고 싶을 때

jwt:
  header: X-AUTH-TOKEN
  secret: yourplanet
  token-validity-time: 1800000 # milliseconds 30 * 60 * 1000