spring:
  config:
    import: classpath:application-secret.properties

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER_NAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true