spring:
  redis:
    host: localhost
    port: 6379

omni:
  id: mlaw12@naver.com
  password: xodid12!@
  host: https://stg-omni.ibapi.kr
  url:
    auth: /v1/auth/token
    alimtalk: /v1/send/alimtalk