spring:
  config:
    import: classpath:alimtalk-secret.properties

omni:
  id: ${OMNI-ALIMTALK-ID}
  password: ${OMNI-ALIMTALK-PASSWORD}
  host: https://omni.ibapi.kr
  url:
    auth: /v1/auth/token
    alimtalk: /v1/send/alimtalk