spring:
  config:
    import: classpath:batch-secret.properties
  datasource:
    url: ${DEV_BATCH_DB_URL}
    username: ${DEV_BATCH_DB_USER_NAME}
    password: ${DEV_BATCH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update    # flyway 도입 전까지