spring:
  datasource:
    url: ${JDBC_DATABASE_URL}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true  #여기는 prinln으로 출력이 나오기 때문에 일단 주석
        format_sql: true