server:
  port: 8091

spring:
  config:
    import: classpath:application-core.yaml
  application:
    name: ypbatch
  profiles:
    active: local
  batch:
    job:
      enabled: false

instagram:
  api-url: https://graph.instagram.com