name: notify

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
    secrets:
      DISCORD_WEBHOOK_URL:
        required: true

jobs:
  notify:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          COMMIT_MESSAGE="$(echo "${{ github.event.head_commit.message }}" | head -n 1)"

          PAYLOAD=$(jq -n --arg content "${{ inputs.title }} - ${COMMIT_MESSAGE}" '{content: $content}')

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}