name: notify

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      title:
        required: true
        type: string

jobs:
  notify:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                     \"content\": \"${{ inputs.title }}: ${{ inputs.status }}\"
                   }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}